const flavorLists = [
  {
    name: "Mango Blaze",
    flavor: "mango-blaze",
    imageFlavorUrl: "https://i.ibb.co/35kgfT84/mango-blaze.webp",
    imageFruteUrl: "https://i.ibb.co/WW64d523/mango-blaze.png",
    imageBacgroundUrl: "https://i.ibb.co/HMTP85M/bg-mango-blaze.webp",
    imageProductShopUrl: "https://i.ibb.co/7dMmc09K/shop-mango-blaze.webp",
    imageBackgroundShop: "https://i.ibb.co/M5tDhS1t/bg-shop-mango-blaze.webp",
    rotation: "md:rotate-[-8deg] rotate-0",
  },
  {
    name: "Berry Rush",
    flavor: "berry-rush",
    imageFlavorUrl: "https://i.ibb.co/JFvQdMps/berry-rush.webp",
    imageFruteUrl: "https://i.ibb.co/20qs3XRv/berry-rush.png",
    imageBacgroundUrl: "https://i.ibb.co/TMwZm03z/bg-berry-rush.webp",
    imageProductShopUrl: "https://i.ibb.co/vx9Rcj3N/shop-berry-rush.webp",
    imageBackgroundShop: "https://i.ibb.co/MW7S2Wt/bg-shop-berry-rush.webp",
    rotation: "md:rotate-[8deg] rotate-0",
  },
  {
    name: "Wild Blueberry",
    flavor: "wild-blueberry",
    imageFlavorUrl: "https://i.ibb.co/fVgSMp0y/wild-blueberry.webp",
    imageFruteUrl: "https://i.ibb.co/RpLmBYz1/wild-blueberry.png",
    imageBacgroundUrl: "https://i.ibb.co/Q3PhnNL5/bg-wild-blueberry.webp",
    imageProductShopUrl: "https://i.ibb.co/nMct7rZ1/shop-wild-blueberry.webp",
    imageBackgroundShop: "https://i.ibb.co/jvxrvzYV/bg-shop-wild-blueberry.webp",
    rotation: "md:rotate-[-8deg] rotate-0",
  },
  {
    name: "Melon Drop",
    flavor: "melon-drop",
    imageFlavorUrl: "https://i.ibb.co/C5cL1s1x/melon-drop.webp",
    imageFruteUrl: "https://i.ibb.co/spf4BgHT/melon-drop.png",
    imageBacgroundUrl: "https://i.ibb.co/pvthR8QC/bg-melon-drop.webp",
    imageProductShopUrl: "https://i.ibb.co/vxbywbT2/shop-melon-drop.webp",
    imageBackgroundShop: "https://i.ibb.co/fGHnBYqt/bg-shop-melom-drop.webp",
    rotation: "md:rotate-[8deg] rotate-0",
  },
  {
    name: "Coconut Cloud",
    flavor: "coconut-cloud",
    imageFlavorUrl: "https://i.ibb.co/yFk2WCKp/coconut-cloud.webp",
    imageFruteUrl: "https://i.ibb.co/nqD7nVgn/coconut-cloud.png",
    imageBacgroundUrl: "https://i.ibb.co/PvXwBH0c/bg-coconut-cloud.webp",
    imageProductShopUrl: "https://i.ibb.co/TDn3M7KF/shop-coconut-cloud.webp",
    imageBackgroundShop: "https://i.ibb.co/Y7q62fjH/bg-shop-coconut-cloud.webp",
    rotation: "md:rotate-[-8deg] rotate-0",
  },
  {
    name: "Lemon Zap",
    flavor: "lemon-zap",
    imageFlavorUrl: "https://i.ibb.co/RkkdTmM3/lemon-zap.webp",
    imageFruteUrl: "https://i.ibb.co/zVHZTNSF/lemon-zap.png",
    imageBacgroundUrl: "https://i.ibb.co/PsGQ42tT/bg-lemon-zap.webp",
    imageProductShopUrl: "https://i.ibb.co/gFD9MZMz/shop-lemon-zap.webp",
    imageBackgroundShop: "https://i.ibb.co/35p8XqDb/bg-shop-lemon-zap.webp",
    rotation: "md:rotate-[8deg] rotate-0",
  },
];

export { flavorLists };